git:
  commitMessage: "[chore] Release v${version}"
  requireBranch: main
github:
  release: true
  web: true
  releaseName: "${version}: "
npm:
  publish: true
hooks:
  after:bump:
    - make package
  after:release: "echo Successfully released ${name} v${version} to ${repo.repository} and NPM."
plugins:
  "@release-it/bumper":
    # The infile gets bumped automatically
    in: package.json
    out:
      - "./pubspec.yaml"
#  "@release-it/keep-a-changelog":
#    filename: "CHANGELOG.md"
#    addVersionUrl: true
#    strictLatest: false
