name: wp_backup
description: Create database and userdata backups for staggered Wordpress releases.
version: 1.0.0-beta.1.2
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  cli_dialog: ^0.5.0
  cli_util: ^0.3.5
  dcli: 1.16.3-beta.1
