name: wp_backup
description: Create database and userdata backups for staggered Wordpress releases.
version: 1.0.0
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  archive: ^3.3.0
  cli_dialog: ^0.5.0
  cli_util: ^0.3.5
  dcli: ^1.30.2
  progress_bar: ^1.0.0
  slugify: ^2.0.0
  yaml: ^3.1.1
